### ISSUE TITLE
node-exporter pod running failed on EKS

### ISSUE THREAD

**Issue by hnhai** [Thakurvaibhav/k8s#11]
Logs: 0/3 nodes are available: 2 node(s) didn't match node selector, 3 node(s) didn't have free ports for the requested pod ports.

**Comment by Thakurvaibhav** [comment]
Hi @hnhai
Is there any other pod running on the nodes which could be occupying port 9100 ?

**Comment by hnhai** [comment]
I don't have permission to check it. Can I change port of node-exporter ?
If change how can I config prometheus to pull metrics from node-exporter. Tks !!!

**Comment by Thakurvaibhav** [comment]
@hnhai Node exporter used `hostNetwork: true`, imo changing the port would not be a great idea. I would suggest looking for applications which are occupying port 9100 on the host.

**Comment by hnhai** [comment]
@Thakurvaibhav thank you very much. I fixed it
