### ISSUE TITLE
Can't get metrics of PersistentVolumeClaim

### ISSUE THREAD

**Issue by hnhai** [Thakurvaibhav/k8s#13]
I need collect below metrics, Pls help me !

- kubelet_volume_stats_available_bytes

- kubelet_volume_stats_capacity_bytes

- kubelet_volume_stats_inodes

- kubelet_volume_stats_inodes_free

- kubelet_volume_stats_inodes_used

- kubelet_volume_stats_used_bytes

**Comment by hnhai** [comment]
https://stackoverflow.com/questions/59332331/missing-metrics-for-persistentvolumeclaim-minikube-prometheus.
here is my question on stackoverflow

**Comment by Thakurvaibhav** [comment]
Hi @hnhai ,
These metrics were initially dropped but there has been some work around fixing them. Please refer:
1. https://github.com/coreos/prometheus-operator/issues/2359
2. https://github.com/kubernetes/kubernetes/pull/76188

**Comment by hnhai** [comment]
@Thakurvaibhav i will check it, thankyou very much !!!
